### ISSUE TITLE
how to inject object_repository and object_manager to validator annotation

### ISSUE THREAD

**Issue by adriandrozdz** [doctrine/DoctrineModule#289]
``` php
    /**
     * @Annotation\Validator({"name":"DoctrineModule\Validator\UniqueObject", 
     *                                        "options":{
     *                                                        "fields":"name",
     *                                                        "object_repository":"..",
     *                                                        "object_manager":"...",
     *                                                       }
     *                                      })
     */
```

Is it possibe to fill in the blank so that it works??

**Comment by cbichis** [comment]
This doesnt seems to work. I added this under form_element_manager or under form_element and doesnt work. Still getting the constructor error...

**Comment by cbichis** [comment]
Adding to Module getFormElementConfig doesnt work too... Same issue...

**Comment by vvaswani** [comment]
@adriandrozdz @cbichis @Ocramius : I'm having a similar problem with a ZF3 app.

```
Error:
Catchable fatal error: Argument 1 passed to DoctrineModule\Validator\UniqueObject::__construct() must be of the type array, none given, called in /var/www/jade/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php on line 32 and defined in /var/www/jade/vendor/doctrine/doctrine-module/src/DoctrineModule/Validator/UniqueObject.php on line 66
```

Not sure why it says "none given" as the array is present in the service config, see below.

Annotation:

```
     * @Annotation\Validator({"name":"DoctrineModule\Validator\UniqueObject"})
```

Module.php:

```
    public function getServiceConfig()
    {
        return [
            'factories' => [
                'Zend\Authentication\AuthenticationService' => function ($serviceManager) {
                    return $serviceManager->get('doctrine.authenticationservice.orm_default');
                },
                'DoctrineModule\Validator\UniqueObject' => function ($serviceManager) {
                    $uniqueObject = new DoctrineModule\Validator\UniqueObject(array(
                        'fields' => 'username',
                        'object_repository' => $serviceManager->get('Doctrine\ORM\EntityManager')->getRepository('Application\Entity\User'),
                        'object_manager' => $serviceManager->get('Doctrine\ORM\EntityManager'),
                    ));
                    return $uniqueObject;
                },
            ],
        ];
    }
```

I also tried placing this in getValidatorConfig and getFormElementsConfig as suggested in this thread, no luck. Please let me know if you were able to get it to work and how. I'll also add this to the docs via a PR once it's working. Thanks in advance.

**Comment by ddelrio1986** [comment]
The correct key in the config would be:

`['form_elements' => ['factories' => []]`

**Comment by vvaswani** [comment]
@ddelrio1986 , thanks for the suggestion. However I tried it and it had no effect:

```
    public function getServiceConfig()
    {
        return [
                'form_elements' => [
                    'factories' => [
                        'DoctrineModule\Validator\UniqueObject' => function ($serviceManager) {
                            $uniqueObject = new \DoctrineModule\Validator\UniqueObject(array(
                                'fields' => 'username',
                                'object_repository' => $serviceManager->get('Doctrine\ORM\EntityManager')->getRepository('Application\Entity\User'),
                                'object_manager' => $serviceManager->get('Doctrine\ORM\EntityManager'),
                            ));
                            return $uniqueObject;
                        }, 
                ]   
            ],
        ];
    }
```

Using the annotation produces the same error:

```
( ! ) Catchable fatal error: Argument 1 passed to DoctrineModule\Validator\UniqueObject::__construct() must be of the type array, none given, called in /var/www/jade/vendor/zendframework/zend-servicemanager/src/Factory/InvokableFactory.php on line 32 and defined in /var/www/jade/vendor/doctrine/doctrine-module/src/DoctrineModule/Validator/UniqueObject.php on line 66
Call Stack
Function	Location
{main}( )	.../index.php:0
include( '/var/www/jade/public/index.php' )	.../index.php:2
Zend\Mvc\Application->run( )	.../index.php:40
Zend\EventManager\EventManager->triggerEventUntil( object(Closure)[101], object(7] )	.../Application.php:332
Zend\EventManager\EventManager->triggerListeners( object(7], object(Closure)[101] )	.../EventManager.php:151
Zend\Mvc\DispatchListener->onDispatch( object(Zend\Mvc\MvcEvent)[97] )	.../
Zend\Mvc\Controller\AbstractController->dispatch( object(ment\Request)[69], object(Zend\Http\PhpEnvironment\Response)[78] )	.../:119
Zend\EventManager\EventManager->triggerEventUntil( object(Closure)[210], object(7] )	.../AbstractController.php:105
Zend\EventManager\EventManager->triggerListeners( object(7], object(Closure)[210] )	.../EventManager.php:151
Zend\Mvc\Controller\AbstractActionController->onDispatch( object(7] )	.../EventManager.php:271
Application\Controller\UserController->saveAction( )	.../ller.php:78
Zend\Form\Annotation\AnnotationBuilder->createForm( object(ser)[261] )	.../UserController.php:137
Zend\Form\Factory->createForm( array(5) )	.../AnnotationBuilder.php:246
Zend\Form\Factory->create( array(6) )	.../Factory.php:177
Zend\Form\Factory->configureForm( object(Zend\Form\Form)[275], array(6) )	.../
Zend\Form\Factory->prepareAndInjectInputFilter( array(3), object(, string(32) )	.../Factory.php:284
Zend\InputFilter\Factory->createInputFilter( array(3) )	.../Factory.php:545
Zend\InputFilter\Factory->createInput( array(3) )	.../Factory.php:357
Zend\InputFilter\Factory->populateValidators( object(atorChain)[310], array(2) )	.../Factory.php:267
Zend\Validator\ValidatorChain->attachByName( string(37), array(0), bool, ??? )	
Zend\Validator\ValidatorChain->plugin( string(37), array(0) )	.../94
Zend\ServiceManager\AbstractPluginManager->get( string(37), array(0) )	.../7
Zend\ServiceManager\ServiceManager->get( string(37) )	.../r.php:143
Zend\ServiceManager\ServiceManager->doCreate( string(37), ??? )	.../95
Zend\ServiceManager\Factory\InvokableFactory->__invoke( object(ServiceManager)[311], string(37), null )	.../ServiceManager.php:747
DoctrineModule\Validator\UniqueObject->__construct( ??? )	.../:32
```

**Comment by ddelrio1986** [comment]
The factory looks correct to me. Seems like the annotation builder isn't using your factory though.

**Comment by vvaswani** [comment]
@ddelrio1986 I've tried to configure the annotation builder to use the factory as below:

Annotation:
` * @Annotation\Validator({"name":"DoctrineModule\Validator\UniqueObject"}`)

Controller:
```
        $builder = new AnnotationBuilder();
        $builder->setFormFactory(new \Zend\Form\Factory($this->c->get(\Zend\Form\FormElementManager::class)));
        $form = $builder->createForm($user);
        ...
```

Module.php:
```
    public function getServiceConfig()
    {
        return [
            'form_elements' => [
                'factories' => [
                    'DoctrineModule\Validator\UniqueObject' => function ($serviceManager) {
                        $uniqueObject = new DoctrineModule\Validator\UniqueObject(array(
                            'fields' => 'username',
                            'object_repository' => $serviceManager->get('Doctrine\ORM\EntityManager')->getRepository('Application\Entity\User'),
                            'object_manager' => $serviceManager->get('Doctrine\ORM\EntityManager'),
                        ));
                        return $uniqueObject;
                    },
                ]
            ]
        ];
    }
```

Error is as follows. Although it says the "object_repository" option isn't present, you can see from the service config that it is.

```
Message:
    Service with name "DoctrineModule\Validator\UniqueObject" could not be created. Reason: Option "object_repository" is required and must be an instance of Doctrine\Common\Persistence\ObjectRepository, nothing given

Stack trace:
    #0 /var/www/jade/vendor/zendframework/zend-servicemanager/src/ServiceManager.php(222): Zend\ServiceManager\ServiceManager->doCreate('DoctrineModule\\...', Array)
    #1 /var/www/jade/vendor/zendframework/zend-servicemanager/src/AbstractPluginManager.php(143): Zend\ServiceManager\ServiceManager->build('DoctrineModule\\...', Array)
    #2 /var/www/jade/vendor/zendframework/zend-validator/src/ValidatorChain.php(97): Zend\ServiceManager\AbstractPluginManager->get('DoctrineModule\\...', Array)
    #3 /var/www/jade/vendor/zendframework/zend-validator/src/ValidatorChain.php(194): Zend\Validator\ValidatorChain->plugin('DoctrineModule\\...', Array)
    #4 /var/www/jade/vendor/zendframework/zend-inputfilter/src/Factory.php(428): Zend\Validator\ValidatorChain->attachByName('DoctrineModule\\...', Array, false)
    #5 /var/www/jade/vendor/zendframework/zend-inputfilter/src/Factory.php(267): Zend\InputFilter\Factory->populateValidators(Object(Zend\Validator\ValidatorChain), Array)
    #6 /var/www/jade/vendor/zendframework/zend-inputfilter/src/Factory.php(357): Zend\InputFilter\Factory->createInput(Array)
    #7 /var/www/jade/vendor/zendframework/zend-form/src/Factory.php(545): Zend\InputFilter\Factory->createInputFilter(Array)
    #8 /var/www/jade/vendor/zendframework/zend-form/src/Factory.php(284): Zend\Form\Factory->prepareAndInjectInputFilter(Array, Object(Zend\Form\Form), 'Zend\\Form\\Facto...')
    #9 /var/www/jade/vendor/zendframework/zend-form/src/Factory.php(114): Zend\Form\Factory->configureForm(Object(Zend\Form\Form), Array)
    #10 /var/www/jade/vendor/zendframework/zend-form/src/Factory.php(177): Zend\Form\Factory->create(Array)
    #11 /var/www/jade/vendor/zendframework/zend-form/src/Annotation/AnnotationBuilder.php(246): Zend\Form\Factory->createForm(Array)
    #12 /var/www/jade/module/Application/src/Controller/UserController.php(135): Zend\Form\Annotation\AnnotationBuilder->createForm(Object(Application\Entity\User))
    #13 /var/www/jade/vendor/zendframework/zend-mvc/src/Controller/AbstractActionController.php(78): Application\Controller\UserController->saveAction()
    #14 /var/www/jade/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\Controller\AbstractActionController->onDispatch(Object(Zend\Mvc\MvcEvent))
    #15 /var/www/jade/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
    #16 /var/www/jade/vendor/zendframework/zend-mvc/src/Controller/AbstractController.php(105): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #17 /var/www/jade/vendor/zendframework/zend-mvc/src/DispatchListener.php(119): Zend\Mvc\Controller\AbstractController->dispatch(Object(Zend\Http\PhpEnvironment\Request), Object(Zend\Http\PhpEnvironment\Response))
    #18 /var/www/jade/vendor/zendframework/zend-eventmanager/src/EventManager.php(271): Zend\Mvc\DispatchListener->onDispatch(Object(Zend\Mvc\MvcEvent))
    #19 /var/www/jade/vendor/zendframework/zend-eventmanager/src/EventManager.php(151): Zend\EventManager\EventManager->triggerListeners(Object(Zend\Mvc\MvcEvent), Object(Closure))
    #20 /var/www/jade/vendor/zendframework/zend-mvc/src/Application.php(332): Zend\EventManager\EventManager->triggerEventUntil(Object(Closure), Object(Zend\Mvc\MvcEvent))
    #21 /var/www/jade/public/index.php(40): Zend\Mvc\Application->run()
    #22 /var/www/jade/index.php(2): include('/var/www/jade/p...')
    #23 {main}
```

Please let me know if you can see what I'm doing wrong. Thanks.
